// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxGisv0oyFfM0o41plTk48VOOKKtCIhQ',
    appId: '1:1025261500030:web:6faccbe7552a7a2c198a2f',
    messagingSenderId: '1025261500030',
    projectId: 'prm393-af7f0',
    authDomain: 'prm393-af7f0.firebaseapp.com',
    storageBucket: 'prm393-af7f0.firebasestorage.app',
    measurementId: 'G-VVJNC848Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoPeylBhdpAGiMW-3DDlpK2TVut1ddPPw',
    appId: '1:1025261500030:android:85c395c28a1ddd34198a2f',
    messagingSenderId: '1025261500030',
    projectId: 'prm393-af7f0',
    storageBucket: 'prm393-af7f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv2slPGrg__ayfdNfysYgM9tzWkDe4ERY',
    appId: '1:1025261500030:ios:a208a4ce85daae2b198a2f',
    messagingSenderId: '1025261500030',
    projectId: 'prm393-af7f0',
    storageBucket: 'prm393-af7f0.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv2slPGrg__ayfdNfysYgM9tzWkDe4ERY',
    appId: '1:1025261500030:ios:a208a4ce85daae2b198a2f',
    messagingSenderId: '1025261500030',
    projectId: 'prm393-af7f0',
    storageBucket: 'prm393-af7f0.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxGisv0oyFfM0o41plTk48VOOKKtCIhQ',
    appId: '1:1025261500030:web:fa0db5e2d1883609198a2f',
    messagingSenderId: '1025261500030',
    projectId: 'prm393-af7f0',
    authDomain: 'prm393-af7f0.firebaseapp.com',
    storageBucket: 'prm393-af7f0.firebasestorage.app',
    measurementId: 'G-DFVQRQE7Q8',
  );
}
